
@startuml
<style>
queue {
   LineThickness: 1
   BackGroundColor: white
   LineColor: black
}
interface {
   BackGroundColor: white
   LineColor: black
}
component {
   BackGroundColor: white
   LineColor: black
}
database {
   BackGroundColor: white
   LineColor: black
}
node {
   BackGroundColor: white
   LineColor: black
}
rectangle{
   LineColor: black
}
arrow {
   LineColor: black
}
</style>

top to bottom direction
'left to right direction

interface "API Request" as Request
rectangle [API Composition] as API

Request --> API

interface "API Request MS 1" as MS1
interface "API Request MS 2" as MS2
interface "API Request MS 3" as MS3

API --> MS1
API --> MS2
API --> MS3

@enduml
