
@startuml
<style>
queue {
   LineThickness: 1
   BackGroundColor: white
   LineColor: black
}
interface {
   BackGroundColor: white
   LineColor: black
}
component {
   BackGroundColor: white
   LineColor: black
}
database {
   BackGroundColor: white
   LineColor: black
}
node {
   BackGroundColor: white
   LineColor: black
}
rectangle{
   LineColor: black
}
arrow {
   LineColor: black
}
</style>

top to bottom direction
'left to right direction
database Database {
  component [Schema B] as ShemaA
  component [Schema A] as ShemaB
  component [Schema C] as ShemaC
}


node Microservices {
   component [MS 1] as MS3
   component [MS 3] as MS2
   component [MS 2] as MS1
}

ShemaA <-- MS3
ShemaA <-- MS2
ShemaA <-- MS1

ShemaB <-- MS3
ShemaB <-- MS2
ShemaB <-- MS1

ShemaC <-- MS3
ShemaC <-- MS2
ShemaC <-- MS1

@enduml
