
@startuml
<style>
queue {
   LineThickness: 1
   BackGroundColor: white
   LineColor: black
}
interface {
   BackGroundColor: white
   LineColor: black
}
component {
   BackGroundColor: white
   LineColor: black
}
database {
   BackGroundColor: white
   LineColor: black
}
node {
   BackGroundColor: white
   LineColor: black
}
rectangle{
   LineColor: black
}
arrow {
   LineColor: black
}
</style>

'top to bottom direction
left to right direction
component WebClient
component MobileClient

node Gateway

node Microservices {
   component MS1
   component MS2
}

WebClient --> Gateway : Request
MobileClient --> Gateway : Request

Gateway -(0- MS1 : :4000
Gateway -(0- MS2 : :4001
@enduml
