
@startuml
<style>
queue {
   LineThickness: 1
   BackGroundColor: white
   LineColor: black
}
interface {
   BackGroundColor: white
   LineColor: black
}
component {
   BackGroundColor: white
   LineColor: black
}
database {
   BackGroundColor: white
   LineColor: black
}
node {
   BackGroundColor: white
   LineColor: black
}
rectangle{
   LineColor: black
   BackGroundColor: white
}
arrow {
   LineColor: black
}
</style>

top to bottom direction
'left to right direction

component Microservice as MS
rectangle "GET /about" as getabout
rectangle "GET /about/health" as GETabouthealth
MS --0 getabout
MS --0 GETabouthealth
MS --( RabbitMQLogs
MS --( RabbitMQEmails
MS --( RabbitMQNotitications

@enduml
