
@startuml
<style>
queue {
   LineThickness: 1
   BackGroundColor: white
   LineColor: black
}
interface {
   BackGroundColor: white
   LineColor: black
}
component {
   BackGroundColor: white
   LineColor: black
}
database {
   BackGroundColor: white
   LineColor: black
}
node {
   BackGroundColor: white
   LineColor: black
}
frame {
   BackGroundColor: white
   LineColor: black
}
rectangle{
   BackGroundColor: white
   LineColor: black
}
arrow {
   LineColor: black
}
</style>

'top to bottom direction
left to right direction

component "MS 1" as MS1
rectangle "Local Transaction" as LT1
MS1 -r- LT1

queue Queue

component "MS 2" as MS2
rectangle "Local Transaction" as LT2
MS2 -r- LT2

MS1 --> Queue : Message/Event
Queue --> MS2 : Message/Event
MS2 --> Queue : Revert Message/Event
Queue --> MS1 : Revert Message/Event
@enduml
